#
# Kafka command dispatcher
#
# Instruction for several config
# topics: A comma-separated list of topics to consume
# zookeeper: A comma-separated Zookeeper connection string
# command: (e.g. 路/usr/bin/php路)
# params: (e.g. 路/data/shell/test.php路)
#
consumer_group : local
topics : raw_click
zookeeper : 10.21.32.226:2181,10.21.32.65:2181,10.21.32.127:2181
command : php
params : e:\t.php
process_number : 10
buff_number : 200
#log_path : e:\kafka.log
